version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - echo Build started on `date`
      - git status
      - npm test
      - coveralls -v < coverage/lcov.info
  post_build:
    commands:
      - echo Build completed on `date`
