version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  pre_build:
    commands:
      - npm i
      - echo $CODEBUILD_WEBHOOK_BASE_REF
      - git checkout $CODEBUILD_WEBHOOK_BASE_REF
  build:
    commands:
      - echo Build started on `date`
      - npm run test:coveralls
  post_build:
    commands:
      - echo Build completed on `date`
