[[sources]]
  name = "global"
  database = "shapes"

  [[sources.layers]]
    minzoom   = 3
    name      = "water"
    table     = "public.water_gen3"
  [[sources.layers.variants]]
      minzoom = 4
      table   = "public.water_gen4"
  [[sources.layers.variants]]
      minzoom = 5
      table   = "public.water_gen5"
  [[sources.layers.variants]]
      minzoom = 6
      table   = "public.water_gen6"
  [[sources.layers.variants]]
      minzoom = 7
      table   = "public.simplified_water_polygons"
  [[sources.layers.variants]]
      minzoom = 8
      table   = "public.water_polygons"

  [[sources.layers]]
    minzoom   = 3
    name      = "bathymetry"
    table     = "public.bathymetry_gen3"
    keys      = ["depth"]
    postfix   = "ORDER BY depth"
  [[sources.layers.variants]]
      minzoom = 4
      table   = "public.bathymetry_gen4"
  [[sources.layers.variants]]
      minzoom = 5
      table   = "public.bathymetry"

  [[sources.layers]]
    minzoom   = 3
    name      = "lakes"
    table     = "public.lakes"
    keys      = ["name"]
    where     = ["minzoom <= !ZOOM!"]

  [[sources.layers]]
    minzoom   = 3
    name      = "urban_areas"
    table     = "public.ne_10m_urban_areas"
    where     = ["min_zoom <= !ZOOM!"]

  [[sources.layers]]
    minzoom   = 3
    name      = "places"
    table     = "public.ne_10m_populated_places_simple"
    keys      = ["name", "featurecla as subclass"]
    where     = ["min_zoom <= !ZOOM!"]
    postfix   = "ORDER BY scalerank"

[[sources]]
  name = "local"
  database = "local"

  [[sources.layers]]
    name      = "landuse"
    minzoom   = 10
    table     = "import.landuse_gen10"
    keys      = ["osm_id as id", "subclass", "area", "name"]
    [[sources.layers.variants]]
      minzoom = 11
      table   = "import.landuse_gen11"
    [[sources.layers.variants]]
      minzoom = 12
      table   = "import.landuse_gen12"
    [[sources.layers.variants]]
      minzoom = 13
      table   = "import.landuse_gen13"
    [[sources.layers.variants]]
      minzoom = 14
      table   = "import.landuse_gen14"
    [[sources.layers.variants]]
      minzoom = 15
      table   = "import.landuse"

  [[sources.layers]]
    name      = "landcover"
    minzoom   = 8
    table     = "import.landcover_gen8"
    keys      = ["osm_id as id", "class", "subclass", "area", "surface", "name"]
    [[sources.layers.variants]]
      minzoom = 9
      table   = "import.landcover_gen9"
    [[sources.layers.variants]]
      minzoom = 10
      table   = "import.landcover_gen10"
    [[sources.layers.variants]]
      minzoom = 11
      table   = "import.landcover_gen11"
    [[sources.layers.variants]]
      minzoom = 12
      table   = "import.landcover_gen12"
    [[sources.layers.variants]]
      minzoom = 13
      table   = "import.landcover_gen13"
    [[sources.layers.variants]]
      minzoom = 14
      table   = "import.landcover_gen14"
    [[sources.layers.variants]]
      minzoom = 15
      table   = "import.landcover"

  [[sources.layers]]
    name    = "waterway"
    minzoom = 8
    table   = "import.waterway_gen8"
    keys    = ["osm_id as id", "subclass", "tunnel", "layer", "name"]
    where   = ["subclass IN('river', 'canal')"]
    [[sources.layers.variants]]
      minzoom = 10
      table   = "import.waterway_gen10"
    [[sources.layers.variants]]
      minzoom = 12
      table   = "import.waterway_gen12"
      where   = ["subclass IN('river', 'canal', 'stream')"]
    [[sources.layers.variants]]
      minzoom = 14
      table   = "import.waterway"
      keys    = ["osm_id as id", "subclass", "tunnel", "layer", "CASE WHEN (name_de <> '') IS NOT FALSE THEN name_de WHEN (name_en <> '') IS NOT FALSE THEN name_en ELSE name END as name"]      
      where   = []
      
  [[sources.layers]]
    name      = "waterarea"
    minzoom   = 8
    table     = "import.waterarea_gen8"
    keys      = ["osm_id as id"]
    [[sources.layers.variants]]
      minzoom = 9
      table   = "import.waterarea_gen9"
    [[sources.layers.variants]]
      minzoom = 10
      table   = "import.waterarea_gen10"
    [[sources.layers.variants]]
      minzoom = 11
      table   = "import.waterarea_gen11"
    [[sources.layers.variants]]
      minzoom = 12
      table   = "import.waterarea_gen12"
    [[sources.layers.variants]]
      minzoom = 13
      table   = "import.waterarea_gen13"
    [[sources.layers.variants]]
      minzoom = 14
      table   = "import.waterarea_gen14"
    [[sources.layers.variants]]
      minzoom = 15
      table   = "import.waterarea"

  [[sources.layers]]
    name      = "roads"
    minzoom   = 8
    table     = "import.roads_gen8"
    keys      = [
      "osm_id as id", 
      "class", 
      "subclass", 
      "oneway", 
      "tracktype", 
      "bridge", 
      "tunnel", 
      "service", 
      "CASE WHEN layer IS NULL THEN 0 ELSE layer END as layer", 
      "rank", 
      "bicycle", 
      "scale", 
      "substring(ref from '\\w+') as ref_prefix", 
      "substring(ref from '\\d+') as ref_num", 
      "NULL as name"]
    [[sources.layers.variants]]
      minzoom = 9
      table   = "import.roads_gen9"
    [[sources.layers.variants]]
      minzoom = 10
      table   = "import.roads_gen10"
    [[sources.layers.variants]]
      minzoom = 11
      table   = "import.roads_gen11"
    [[sources.layers.variants]]
      minzoom = 12
      table   = "import.roads_gen12"
    [[sources.layers.variants]]
      minzoom = 13
      table   = "import.roads_gen13"
    [[sources.layers.variants]]
      minzoom = 14
      table   = "import.roads_gen14"
    [[sources.layers.variants]]
      minzoom = 15
      table   = "import.roads_gen15"
    [[sources.layers.variants]]
      minzoom = 16
      table   = "import.roads"
      keys      = [
        "osm_id as id", 
        "class", 
        "subclass", 
        "oneway", 
        "tracktype", 
        "bridge", 
        "tunnel", 
        "service", 
        "CASE WHEN layer IS NULL THEN 0 ELSE layer END as layer", 
        "rank", 
        "bicycle", 
        "scale", 
        "substring(ref from '\\w+') as ref_prefix", 
        "substring(ref from '\\d+') as ref_num", 
        "name"]
      postfix = "ORDER BY rank DESC"


  [[sources.layers]]
    minzoom   = 11
    name      = "cycleroute"
    sql       = "SELECT row_number() over () as gid, ref, name, ST_AsMvtGeom(ST_LineMerge(ST_Collect(geometry)), !BBOX!) AS geom from import.cycleroute where (geometry && !BBOX!) AND ST_GeometryType(geometry)='ST_LineString' group by ref, name order by ref desc NULLS last, name desc NULLS last"

  [[sources.layers]]
    minzoom   = 9
    name      = "railway"
    table     = "import.railway"
    keys      = ["id", "class", "subclass", "zorder", "bridge", "tunnel", "service"]
    where     = ["subclass NOT IN('subway', 'tram')", "(attraction <> '') IS NOT TRUE"]
    [[sources.layers.variants]]
      minzoom   = 15
      where     = ["(attraction <> '') IS NOT TRUE"]

  [[sources.layers]]
    minzoom   = 10
    name      = "transportation"
    table     = "import.transportation"
    keys      = ["id", "class", "subclass", "CASE WHEN (name_de <> '') IS NOT FALSE THEN name_de WHEN (name_en <> '') IS NOT FALSE THEN name_en ELSE name END as name"]
    where     = ["NOT ST_IsClosed(geometry)"]


  [[sources.layers]]
    minzoom   = 10
    name      = "manmade"
    sql       = "select osm_id as id, ST_AsMvtGeom(geometry, !BBOX!) as geom, class, subclass, ST_Length(geometry)::integer as length, ST_IsClosed(geometry) as polygon from import.manmade_lines_gen13 WHERE (geometry && !BBOX!)"
    [[sources.layers.variants]]
      minzoom = 14
      sql       = """select osm_id as id, ST_AsMvtGeom(geometry, !BBOX!) as geom, class, subclass, ST_Length(geometry)::integer as length, ST_IsClosed(geometry) as polygon from import.manmade_lines WHERE (geometry && !BBOX!) 
                  UNION ALL
                  select osm_id as id, ST_AsMvtGeom(geometry, !BBOX!) as geom, class, subclass, ST_Perimeter(geometry)::integer as length, TRUE as polygon from import.manmade_polygons WHERE (geometry && !BBOX!) 
                  UNION ALL
                  select osm_id as id, ST_AsMvtGeom(geometry, !BBOX!) as geom, class, subclass, 0 as length, FALSE as polygon from import.manmade_points WHERE (geometry && !BBOX!)
                  """

  [[sources.layers]]
    minzoom   = 14
    name      = "piste"
    table     = "import.piste"
    keys      = ["id", "difficulty"]
    where     = ["NOT ST_IsClosed(geometry)"]

  [[sources.layers]]
    minzoom   = 14
    name      = "admin"
    table     = "import.admin"
    keys      = ["id", "ref", "level"]

  [[sources.layers]]
    minzoom   = 13
    maxzoom   = 15
    name      = "buildings-large"
    table     = "import.buildings_gen14"
    keys      = ["id"]
    where     = ["ST_Area(geometry)>10000"]

  [[sources.layers]]
    minzoom   = 14
    name      = "buildings"
    table     = "import.buildings_gen14"
    keys      = ["id"]
    [[sources.layers.variants]]
      minzoom = 15
      table   = "import.buildings"

  [[sources.layers]]
    minzoom   = 18
    name      = "housenumbers"
    table     = "import.housenumbers"
    keys      = ["osm_id as id", "number", "name"]

  [[sources.layers]]
    name      = "waterlabels"
    minzoom   = 8
    table     = "import.label_waterarea_gen8"
    keys      = ["osm_id as id", "subclass", "area", "ele", "name"]
    [[sources.layers.variants]]
      minzoom = 10
      table   = "import.label_waterarea_gen10"
    [[sources.layers.variants]]
      minzoom = 12
      table   = "import.label_waterarea_gen12"
    [[sources.layers.variants]]
      minzoom = 14
      table   = "import.label_waterarea_gen14"
    [[sources.layers.variants]]
      minzoom = 16
      table   = "import.label_waterarea"

  [[sources.layers]]
    minzoom   = 8
    name      = "label"
    table     = "import.label"
    prefix    = "DISTINCT ON(pop, name)"
    keys      = ["row_number() over (ORDER by pop desc NULLS LAST) as id", "class", "subclass", "name", "ele", "pop"]
    postfix   = "ORDER BY pop DESC NULLS LAST, name"

  [[sources.layers]]
    minzoom   = 11
    name      = "poi"
    table     = "import.poi_cluster_gen11"
    keys      = ["id", "count", "class", "subclass", "name", "ele", "access", "subway", "religion", "parking"]
    [[sources.layers.variants]]
      minzoom = 12
      table   = "import.poi_cluster_gen12"
    [[sources.layers.variants]]
      minzoom = 13
      table   = "import.poi_cluster_gen13"
    [[sources.layers.variants]]
      minzoom = 14
      table   = "import.poi_cluster_gen14"
    [[sources.layers.variants]]
      minzoom = 15
      table   = "import.poi_cluster_gen15"
    [[sources.layers.variants]]
      minzoom = 16
      table   = "import.poi_cluster_gen16"
    [[sources.layers.variants]]
      minzoom = 17
      table   = "import.poi_cluster_gen17"
    [[sources.layers.variants]]
      minzoom = 18
      table   = "import.poi"
      keys    = ["osm_id as id", "1 as count", "class", "subclass", "name", "ele", "access", "subway", "religion", "parking"]

